services:
  - type: web
    name: budget-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://keape86:trombino86@budgetapp.enqupoz.mongodb.net/budget-app?retryWrites=true&w=majority&appName=budgetapp
      - key: JWT_SECRET
        value: mySecretKey123
    healthCheckPath: /api/health