services:
  - type: web
    name: budget-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
    healthCheckPath: /api/health